FROM python:3.12-slim

WORKDIR /app

# Copy model scripts and data folder
COPY ./pipeline ./pipeline
COPY ./data ./data
COPY ./entrypoint_pipeline.sh ./

# Install requirements
RUN pip install -r pipeline/requirements.txt
# RUN pip install --no-cache-dir -r pipeline/requirements.txt

# Set default command (can be overridden by docker-compose entrypoint)
CMD ["sh", "entrypoint_pipeline.sh"]
