
services:
  db:
    image: postgres:15
    container_name: webapp_db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./data/indexes.sql:/docker-entrypoint-initdb.d/indexes.sql
    env_file: .env

  web:
    build: .
    container_name: webapp_web
    restart: always
    ports:
      - "8050:8050"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    env_file: .env
    volumes:
      - ./data:/app/data

  pipeline:
    build:
      context: .
      dockerfile: Dockerfile.pipeline
    container_name: webapp_pipeline
    restart: "no"
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./data:/app/data
      - ./pipeline:/app/pipeline
    env_file: .env
    entrypoint: ["sh", "/app/entrypoint_pipeline.sh"]


volumes:
  db_data:

