import os

DATABASE_USER = "postgres"
DATABASE_PASSWORD = ""
DATABASE_HOST = "localhost"
DATABASE_PORT = "5432"
DATABASE_NAME = "psynamic"

DATABASE_URL = os.getenv("DATABASE_URL", f'postgresql://{DATABASE_USER}:{DATABASE_PASSWORD}@{DATABASE_HOST}:{DATABASE_PORT}/{DATABASE_NAME}')