FROM python:3.12-slim

WORKDIR /app

# Set timezone to Europe/Zurich
RUN apt-get update && apt-get install -y tzdata
ENV TZ=Europe/Zurich
RUN ln -snf /usr/share/zoneinfo/Europe/Zurich /etc/localtime && echo "Europe/Zurich" > /etc/timezone

# Copy model scripts and data folder
COPY ./pipeline/requirements.txt ./requirements.txt

# Install requirements
RUN pip install -r requirements.txt
# RUN pip install --no-cache-dir -r pipeline/requirements.txt
CMD ["sh", "/app/run_pipeline.sh"]